/* Generated by the Nim Compiler v1.4.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var F={procname:"module test_error2",prev:framePtr,filename:"/Users/pinney/Documents/GitHub/antlr4nim/example/test_error2.nim",line:0};
framePtr = F;
framePtr = F.prev;
var F={procname:"module test_error2",prev:framePtr,filename:"/Users/pinney/Documents/GitHub/antlr4nim/example/test_error2.nim",line:0};
framePtr = F;
F.line = 5;
import fs from 'fs'
# ...

framePtr = F.prev;
var F={procname:"module test_error2",prev:framePtr,filename:"/Users/pinney/Documents/GitHub/antlr4nim/example/test_error2.nim",line:0};
framePtr = F;
framePtr = F.prev;
